declare module "lucide-react" {
  import type { FC, SVGProps } from "react"
  type IconProps = SVGProps<SVGSVGElement> & { size?: number }
  type Icon = FC<IconProps>
  export const ArrowDown: Icon
  export const ArrowLeft: Icon
  export const ArrowUp: Icon
  export const Archive: Icon
  export const Award: Icon
  export const BarChart3: Icon
  export const Bell: Icon
  export const Bookmark: Icon
  export const BookOpen: Icon
  export const Calendar: Icon
  export const Check: Icon
  export const CheckCircle: Icon
  export const ChevronLeft: Icon
  export const ChevronRight: Icon
  export const Clock: Icon
  export const Download: Icon
  export const Edit: Icon
  export const Eye: Icon
  export const EyeOff: Icon
  export const Facebook: Icon
  export const FileDown: Icon
  export const FileText: Icon
  export const Filter: Icon
  export const Globe: Icon
  export const Headphones: Icon
  export const Heart: Icon
  export const HelpCircle: Icon
  export const History: Icon
  export const Home: Icon
  export const Image: Icon
  export const Instagram: Icon
  export const LayoutPanelTop: Icon
  export const Link2: Icon
  export const Loader2: Icon
  export const Lock: Icon
  export const LogOut: Icon
  export const Mail: Icon
  export const MapPin: Icon
  export const Megaphone: Icon
  export const Menu: Icon
  export const MessageCircle: Icon
  export const Minus: Icon
  export const Package: Icon
  export const Pen: Icon
  export const Pencil: Icon
  export const PenTool: Icon
  export const PencilLine: Icon
  export const PencilOff: Icon
  export const PencilRuler: Icon
  export const Phone: Icon
  export const PhoneCall: Icon
  export const Play: Icon
  export const Plus: Icon
  export const RefreshCw: Icon
  export const RotateCw: Icon
  export const ScrollText: Icon
  export const Search: Icon
  export const Send: Icon
  export const Settings: Icon
  export const ShoppingBag: Icon
  export const ShoppingCart: Icon
  export const Sparkles: Icon
  export const SquarePen: Icon
  export const Star: Icon
  export const Trash2: Icon
  export const Upload: Icon
  export const User: Icon
  export const Users: Icon
  export const Video: Icon
  export const X: Icon
}
